### ISSUE TITLE
The link to Baidu Cloud has been deleted

### ISSUE THREAD

**Issue by MickeyLLG** [whisney/NIR-ISL2021-Transfer-learning#1]
Could the authors redistribute one? thank you.

**Comment by whisney** [comment]
Sorry!
The download link has been updated.

**Comment by MickeyLLG** [comment]
Thank you so much! I have closed the issue on github.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月29日(星期二) 凌晨0:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whisney/NIR-ISL2021-Transfer-learning] The link to Baidu Cloud has been deleted (#1)





 
Sorry!
 The download link has been updated.
