### ISSUE TITLE
About model inference have some problems

### ISSUE THREAD

**Issue by JH95-ai** [whisney/NIR-ISL2021-Transfer-learning#3]
I read predict code.Find predict picture need load five models.and for input picture augmented to four picture .Finally,mean this twenty result to get predict. My problems is following:
1.Selection of five models.Is there any basis for that?Whether each fold chooses the best.
2.your train have  already applied flip and gamma augmented.whether need predict used this again.
 Looking forward to your reply~

**Comment by whisney** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "whisney/NIR-ISL2021-Transfer-learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月12日(星期一) 上午8:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[whisney/NIR-ISL2021-Transfer-learning] About model inference have some problems (#3)





 
I read predict code.Find predict picture need load five models.and for input picture augmented to four picture .Finally,mean this twenty result to get predict. My problems is following:
 1.Selection of five models.Is there any basis for that?Whether each fold chooses the best.
 2.your train have  already applied flip and gamma augmented.whether need predict used this again.
 Looking forward to your reply~

**Comment by whisney** [comment]
> I read predict code.Find predict picture need load five models.and for input picture augmented to four picture .Finally,mean this twenty result to get predict. My problems is following:
> 1.Selection of five models.Is there any basis for that?Whether each fold chooses the best.
> 2.your train have already applied flip and gamma augmented.whether need predict used this again.
> Looking forward to your reply~

1. The only criterion for choosing a baseline model or a transfer learning model for a specific fold is its performance on the validating set.
2. Test time augmentation (TTA) is a popular and used trick in competitions, which can improve the robustness of the model.

**Comment by JH95-ai** [comment]
ok I see.Thanks your reply.
