### ISSUE TITLE
Baidu link

### ISSUE THREAD

**Issue by agiardina** [whisney/NIR-ISL2021-Transfer-learning#4]
Hi, 
I think it's very hard to use the Baidu link to download the model outside China. Is there any change to get another method to download the model?

Thanks.
Andrea

**Comment by whisney** [comment]
[[Google Drive]](https://drive.google.com/drive/folders/1dmRIg5oTIALqrZheJq3baZ5MQ89Em8aM?usp=sharing) link has been provided.

**Comment by agiardina** [comment]
Thanks a lot, @whisney.
Really appreciated.

Andrea
